technical_test/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"

  resources :short_sequences
  resources :long_sequences

end

technical_test/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

technical_test/app/models/long_sequence.rb
class LongSequence < ApplicationRecord
	self.table_name = "LongSequence"

	validates :nb_images_on_sd, :numericality =>
	{ 
		:greater_than_or_equal_to => 0,
		message: "Your nb_images_on_sd number should be greater than zero or equal"
	}
	validates :nb_images_uploaded, :numericality =>
	{ 
		:greater_than_or_equal_to => 0,
		message: "Your nb_images_uploaded number should be greater than zero or equal"
	}
end

technical_test/app/models/short_sequence.rb
class ShortSequence < ApplicationRecord
	self.table_name = "ShortSequence"

	def return_end_time(start_time, duration_time)
		date_to_sec = convert_date_to_timestamp(start_time)
		duration_to_sec = convert_min_to_sec(duration_time)
		return date_to_sec + duration_to_sec
	end

	def convert_date_to_timestamp(date)
		return date.to_i
	end

	def convert_min_to_sec(duration_time)
		return duration_time.minutes.to_i
	end

	#get all the sequences that will not allow our current sequence
	def get_array_of_conflict(array)
		puts "Trying to get all the sequences"
		puts "Then calculate the end point of each sequence"
		puts "If the Start Time of my sequence is bigger than the Start Time + Duration Time of each other Sequences"
		puts "And if the Start Time + the Duration Time of my sequence is smaller than the Start Time of every other Sequences"
		puts "So, the current sequence doesn't overlap and we can add it to the Database."
		return "end"
	end

	def are_there_any_conflict(array)
		if array.size>0
			return true
		end
		return false
	end

	validates :interval, :numericality =>
	{ 
		:greater_than_or_equal_to => 0,
		message: "Your interval number should be greater than zero or equal"
	}
	validates :duration, :numericality =>
	{ 
		:greater_than_or_equal_to => 0,
		message: "Your duration number should be greater than zero or equal"
	}
	validates :nb_images_on_sd, :numericality =>
	{ 
		:greater_than_or_equal_to => 0,
		message: "Your nb_images_on_sd number should be greater than zero or equal"
	}
	validates :nb_images_uploaded, :numericality =>
	{ 
		:greater_than_or_equal_to => 0,
		message: "Your nb_images_uploaded number should be greater than zero or equal"
	}

end

technical_test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

technical_test/app/controllers/long_sequences_controller.rb
class LongSequencesController < ApplicationController
	def index
		@longSequence = LongSequence.all
	end

	def show
		@longSequence = LongSequence.find(params[:id])
	end

	def edit
		@longSequence = LongSequence.find(params[:id])
	end

	def update
		@longSequence = LongSequence.find(params[:id])
		
		if @longSequence.update(post_params)
			redirect_to long_sequences_path

		else
			render :show
		end
	end

	def new
		@longSequence = LongSequence.new
	end

	def create
		@longSequence = LongSequence.create(post_params)
		redirect_to long_sequences_path
 
	end

	def destroy
		@longSequence = LongSequence.find(params[:id])

		@longSequence.destroy
		
		redirect_to long_sequences_path
	end

	private

	def post_params
		params.require(:long_sequence).permit(:tikee_id, :name, :description, :start, :end, :upload_to_cloud, :image_format, :keep_local_copy, :infinite_duration, :sequence_id, :shooting_status, :nb_images_on_sd, :nb_images_uploaded)
	end

end

technical_test/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	
	def home
	end
	
	def salut
		@name = params[:name]
	end
end

technical_test/app/controllers/short_sequences_controller.rb
class ShortSequencesController < ApplicationController

	def index
		@shortSequence = ShortSequence.all
		@shortSequenceJson = @shortSequence.to_json()
	end

	def show
		@shortSequence = ShortSequence.find(params[:id])
	end

	def edit
		@shortSequence = ShortSequence.find(params[:id])
	end

	def update
		@shortSequence = ShortSequence.find(params[:id])

		if @shortSequence.update(get_post_params)
		    redirect_to short_sequences_path
		else
			render :show
		end
	end

	def new
		@shortSequence = ShortSequence.new
	end

	def create
		##
		#array_short_sequences =  ShortSequence.all

		#ength_conflict = get_array_of_conflict(array_short_sequences)
		#overlaps = are_there_any_conflict(length_conflict)

		#if overlaps
		#    redirect_to short_sequences_path
		#else
		#	@shortSequence = ShortSequence.create(get_post_params)
		#end
		@shortSequence = ShortSequence.create(get_post_params)
		redirect_to short_sequences_path
 
	end

	def destroy
		@shortSequence = ShortSequence.find(params[:id])

		@shortSequence.destroy
		
		redirect_to short_sequences_path
 
	end

	private

	def get_post_params
		params.require(:short_sequence).permit(:tikee_id, :name, :description, :start, :interval, :duration, :upload_to_cloud, :image_format, :keep_local_copy, :sequence_id, :shooting_status, :nb_images_on_sd, :nb_images_uploaded)
	end

end

technical_test/app/helpers/application_helper.rb
module ApplicationHelper
end

technical_test/app/helpers/short_sequence_helper.rb
module ShortSequenceHelper
end

technical_test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechnicalTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <a class="my-0 mr-md-auto font-weight-normal" href="<%= root_path %>">Chris Website</a>
      </div>
    </header>
    <div class="container" style="padding-top: 5rem">
      <%= yield %>
    </div>
  </body>
</html>

technical_test/app/views/long_sequences/edit.html.erb
<h1>Edit a Tikee</h1>

<%= form_for @longSequence do |f| %>
	<div class="form-group">
		<label>Name of the Tikee</label>
		<%= f.text_field :name, class: "form-control"%>
		<label>Id</label>
		<%= f.number_field :tikee_id, class: "form-control"%>
		<label>Description</label>
		<%= f.text_field :description, class: "form-control"%>
		<label>start</label>
		<%= f.datetime_field :start, class: "form-control"%>
		<label>end</label>
		<%= f.datetime_field :end, class: "form-control"%>
		<label>upload_to_cloud</label>
		<%= f.check_box :upload_to_cloud %><br>
		<label>image_format</label>
		<%= f.text_field :image_format, class: "form-control"%>
		<label>keep_local_copy</label>
		<%= f.check_box :keep_local_copy %><br>
		<label>infinite_duration</label>
		<%= f.check_box :infinite_duration%><br>
		<label>sequence_id</label>
		<%= f.number_field :sequence_id, class: "form-control"%>
		<label>shooting_status</label>
		<%= f.text_field :shooting_status, class: "form-control"%>
		<label>nb_images_on_sd</label>
		<%= f.number_field :nb_images_on_sd, class: "form-control"%>
		<label>nb_images_uploaded</label>
		<%= f.number_field :nb_images_uploaded, class: "form-control"%>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">
			Save
		</button>
	</div>
<% end %>

technical_test/app/views/long_sequences/index.html.erb
<h2>List of all the Long Sequences</h2>
<a href="<%= new_long_sequence_path %>" class="btn btn-success">Add a new Tikee</a>
<br>
<br>

<% @longSequence.each do |longsequence| %>
	<a href="<%= long_sequence_path(longsequence.id) %>" class="btn btn-primary" role="button" aria-pressed="true">Tikee n°<%= longsequence.tikee_id %></a>
<% end %>

technical_test/app/views/long_sequences/new.html.erb
<h1>Add a new Tikee</h1>

<%= form_for @longSequence do |f| %>
	<div class="form-group">
		<label>Name of the Tikee</label>
		<%= f.text_field :name, class: "form-control"%>
		<label>Id</label>
		<%= f.number_field :tikee_id, class: "form-control"%>
		<label>Description</label>
		<%= f.text_field :description, class: "form-control"%>
		<label>start</label>
		<%= f.datetime_field :start, class: "form-control"%>
		<label>end</label>
		<%= f.datetime_field :end, class: "form-control"%>
		<label>upload_to_cloud</label>
		<%= f.check_box :upload_to_cloud %><br>
		<label>image_format</label>
		<%= f.text_field :image_format, class: "form-control"%>
		<label>keep_local_copy</label>
		<%= f.check_box :keep_local_copy %><br>
		<label>infinite_duration</label>
		<%= f.check_box :infinite_duration%><br>
		<label>sequence_id</label>
		<%= f.number_field :sequence_id, class: "form-control"%>
		<label>shooting_status</label>
		<%= f.text_field :shooting_status, class: "form-control"%>
		<label>nb_images_on_sd</label>
		<%= f.number_field :nb_images_on_sd, class: "form-control"%>
		<label>nb_images_uploaded</label>
		<%= f.number_field :nb_images_uploaded, class: "form-control"%>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">
			Save
		</button>
	</div>
<% end %>

technical_test/app/views/long_sequences/show.html.erb
<a href="<%= long_sequence_path(@longSequence.id)%>" class="float-right btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE" style="margin-left: 20px">Remove</a>
<a href="<%= edit_long_sequence_path(@longSequence.id)%>" class="float-right btn btn-warning">Edit</a>
<br>
<br>
<ul class="list-group">
	<li class="list-group-item active"><h2>Details of the Tikee n°<%= @longSequence.id %> in the Long Sequences</h2></li>
	<li class="list-group-item">name : <%= @longSequence.name %></li>
	<li class="list-group-item">tikee_id : <%= @longSequence.tikee_id %></li>
	<li class="list-group-item">description : <%= @longSequence.description %></li>
	<li class="list-group-item">start : <%= @longSequence.start %></li>
	<li class="list-group-item">end : <%= @longSequence.end %></li>
	<li class="list-group-item">upload_to_cloud : <%= @longSequence.upload_to_cloud %></li>
	<li class="list-group-item">image_format : <%= @longSequence.image_format %></li>
	<li class="list-group-item">keep_local_copy : <%= @longSequence.keep_local_copy %></li>
	<li class="list-group-item">infinite_duration : <%= @longSequence.infinite_duration %></li>
	<li class="list-group-item">sequence_id : <%= @longSequence.sequence_id %></li>
	<li class="list-group-item">shooting_status : <%= @longSequence.shooting_status %></li>
	<% if @longSequence.errors[:nb_images_on_sd].count >0 %>
		<li class="list-group-item" style="color:red"><%= @longSequence.errors[:nb_images_on_sd].first %></li>
	<% end %>
	<li class="list-group-item">nb_images_on_sd : <%= @longSequence.nb_images_on_sd %></li>
	<% if @longSequence.errors[:nb_images_uploaded].count >0 %>
		<li class="list-group-item" style="color:red"><%= @longSequence.errors[:nb_images_uploaded].first %></li>
	<% end %>
	<li class="list-group-item">nb_images_uploaded : <%= @longSequence.nb_images_uploaded %></li>
</ul>

technical_test/app/views/pages/home.html.erb
<h1>Welcome to my test !</h1>


<p>Let you go though the CRUD I built and let me know what you think about it ! Enjoy !</p>


<div class="row">
	<div class="col">
		<a href="<%= short_sequences_path %>" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Edit Short Sequence</a>
	</div>
	<div class="col">
		<a href="<%= long_sequences_path %>" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Edit Long Sequence</a>
	</div>
</div>

technical_test/app/views/short_sequences/edit.html.erb
<h1>Edit a Tikee</h1>

<%= form_for @shortSequence do |f| %>
	<div class="form-group">
		<label>Name of the Tikee</label>
		<%= f.text_field :name, class: "form-control"%>
		<label>Id</label>
		<%= f.number_field :tikee_id, class: "form-control"%>
		<label>Description</label>
		<%= f.text_field :description, class: "form-control"%>
		<label>start</label>
		<%= f.datetime_field :start, class: "form-control"%>
		<label>interval</label>
		<%= f.number_field :interval, class: "form-control"%>
		<label>duration</label>
		<%= f.number_field :duration, class: "form-control"%>
		<label>upload_to_cloud</label>
		<%= f.check_box :upload_to_cloud %><br>
		<label>image_format</label>
		<%= f.text_field :image_format, class: "form-control"%>
		<label>keep_local_copy</label>
		<%= f.check_box :keep_local_copy %><br>
		<label>sequence_id</label>
		<%= f.number_field :sequence_id, class: "form-control"%>
		<label>shooting_status</label>
		<%= f.text_field :shooting_status, class: "form-control"%>
		<label>nb_images_on_sd</label>
		<%= f.number_field :nb_images_on_sd, class: "form-control"%>
		<label>nb_images_uploaded</label>
		<%= f.number_field :nb_images_uploaded, class: "form-control"%>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">
			Save
		</button>
	</div>
<% end %>

technical_test/app/views/short_sequences/index.html.erb
<h2>List of all the Short Sequences</h2>
<a href="<%= new_short_sequence_path %>" class="btn btn-success">Add a new Tikee</a>
<br>
<br>

<% @shortSequence.each do |shortsequence| %>
	<a href="<%= short_sequence_path(shortsequence.id) %>" class="btn btn-primary" role="button" aria-pressed="true">
		Tikee n°<%= shortsequence.tikee_id %>
	</a>
<% end %>

<br>
<br>
<br>




<span>For information : <br>
Here is the Json object required</span>
<%= @shortSequenceJson %>

technical_test/app/views/short_sequences/new.html.erb
<h1>Add a new Tikee</h1>

<%= form_for @shortSequence do |f| %>
	<div class="form-group">
		<label>Name of the Tikee</label>
		<%= f.text_field :name, class: "form-control"%>
		<label>Id</label>
		<%= f.number_field :tikee_id, class: "form-control"%>
		<label>Description</label>
		<%= f.text_field :description, class: "form-control"%>
		<label>start</label>
		<%= f.datetime_field :start, class: "form-control"%>
		<label>interval</label>
		<%= f.number_field :interval, class: "form-control"%>
		<label>duration</label>
		<%= f.number_field :duration, class: "form-control"%>
		<label>upload_to_cloud</label>
		<%= f.check_box :upload_to_cloud %><br>
		<label>image_format</label>
		<%= f.text_field :image_format, class: "form-control"%>
		<label>keep_local_copy</label>
		<%= f.check_box :keep_local_copy %><br>
		<label>sequence_id</label>
		<%= f.number_field :sequence_id, class: "form-control"%>
		<label>shooting_status</label>
		<%= f.text_field :shooting_status, class: "form-control"%>
		<label>nb_images_on_sd</label>
		<%= f.number_field :nb_images_on_sd, class: "form-control"%>
		<label>nb_images_uploaded</label>
		<%= f.number_field :nb_images_uploaded, class: "form-control"%>
	</div>
	<div class="form-group">
		<button type="submit" class="btn btn-primary">
			Save
		</button>
	</div>
<% end %>

technical_test/app/views/short_sequences/show.html.erb
<a href="<%= short_sequence_path(@shortSequence.id)%>" class="float-right btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE" style="margin-left: 20px">Remove</a>
<a href="<%= edit_short_sequence_path(@shortSequence.id)%>" class="float-right btn btn-warning">Edit</a>
<br>
<br>
<ul class="list-group">
	<li class="list-group-item active"><h2>Details of the Tikee n°<%= @shortSequence.id %> in the Short Sequences</h2></li>
	<li class="list-group-item">name : <%= @shortSequence.name %></li>
	<li class="list-group-item">tikee_id : <%= @shortSequence.tikee_id %></li>
	<li class="list-group-item">description : <%= @shortSequence.description %></li>
	<li class="list-group-item">start : <%= @shortSequence.start %></li>
	<% if @shortSequence.errors[:interval].count >0 %>
		<li class="list-group-item" style="color:red"><%= @shortSequence.errors[:interval].first %></li>
	<% end %>
	<li class="list-group-item">interval : <%= @shortSequence.interval %></li>
	<% if @shortSequence.errors[:duration].count >0 %>
		<li class="list-group-item" style="color:red"><%= @shortSequence.errors[:duration].first %></li>
	<% end %>
	<li class="list-group-item">duration : <%= @shortSequence.duration %></li>
	<li class="list-group-item">upload_to_cloud : <%= @shortSequence.upload_to_cloud %></li>
	<li class="list-group-item">image_format : <%= @shortSequence.image_format %></li>
	<li class="list-group-item">keep_local_copy : <%= @shortSequence.keep_local_copy %></li>
	<li class="list-group-item">sequence_id : <%= @shortSequence.sequence_id %></li>
	<li class="list-group-item">shooting_status : <%= @shortSequence.shooting_status %></li>
	<% if @shortSequence.errors[:nb_images_on_sd].count >0 %>
		<li class="list-group-item" style="color:red"><%= @shortSequence.errors[:nb_images_on_sd].first %></li>
	<% end %>
	<li class="list-group-item">nb_images_on_sd : <%= @shortSequence.nb_images_on_sd %></li>
	<% if @shortSequence.errors[:nb_images_uploaded].count >0 %>
		<li class="list-group-item" style="color:red"><%= @shortSequence.errors[:nb_images_uploaded].first %></li>
	<% end %>
	<li class="list-group-item">nb_images_uploaded : <%= @shortSequence.nb_images_uploaded %></li>
</ul>